name: admin_dashboard
description: "admin_dashboard"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  fl_chart: ^0.63.0
  intl: ^0.20.0
  image_picker: ^1.0.4
  file_picker: ^6.1.1
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  provider: ^6.1.1
  csv: ^5.0.2
  path_provider: ^2.1.2
  file_saver: ^0.2.2
  url_launcher: ^6.1.7
  iconsax_flutter: ^1.0.1
  font_awesome_flutter: ^10.5.0
  dropdown_search: ^5.0.6
  unicons: ^3.0.0
  lucide_icons: ^0.257.0
  flutter_speed_dial: ^7.0.0
  uuid: ^4.5.1


dev_dependencies:
  intl_utils: ^2.5.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
    - family: Droid
      fonts:
        - asset: assets/fonts/DroidSansArabic.ttf
